knp_snappy:
    pdf:
        enabled:    true
        binary:     '%kernel.project_dir%/vendor/h4cc/wkhtmltopdf'
        options:    []
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage
        options:    []
