twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
      UserNotification: "@User.Notification"
      UserProfile: "@User.Profile"

when@test:
    twig:
        strict_variables: true
